#+BEGIN_HTML
---
layout: post
title: Online Thesaurus APIs
categories:
- API
- code
- internet
---
#+END_HTML

** The problem?
I need an online API for finding synonyms in emacs for a project I'm planning on playing around with. Basically allowing me to find synonyms for words within emacs.

** Dictionary.com
*Limits:* 
 - Only I can use the key, others have to get there own.
 - Up to two days to get a key.

After I found this out, I decided dictionary.com was not a good match for my project.

** Words.bighugelabs.com/api.php
*Limits:*
 - Only I can use the key, others have to get there own.
 - "Only" 10,000 requests a day for free. Not relevant for my purposes.

10,000 requests a day should be more than sufficient for *my* purposes and for anyone it is, there is the option to pay more to get more requests. As such, this should be good API.

** Find a list
Finding a list would be ideal, I've yet to find a good one. I'm going to keep looking for one, but to proceed I'm going to with an API.

** Conclusion
My plan is to use an API, I'll cache the results locally. I'll look over the terms of service and build up the default cache that will be distributed with it.

*Let me know if you know of any good lists of synonyms*
